import { chromium } from 'playwright';
import path from 'path';
const dir = path.dirname(new URL(import.meta.url).pathname);
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 960, height: 540 } });
await ctx.addInitScript(() => { localStorage.setItem('sp_settings', JSON.stringify({ quality: 2 })); });
const page = await ctx.newPage(); const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.route('https://cdn.jsdelivr.net/npm/three@0.186.1/**', (route) => { const u = new URL(route.request().url()); route.fulfill({ path: path.join(dir, 'node_modules/three', u.pathname.replace('/npm/three@0.186.1/', '')), contentType: 'application/javascript' }); });
await page.route('https://cdn.jsdelivr.net/npm/n8ao@2.0.1/**', (route) => route.fulfill({ path: path.join(dir, 'node_modules/n8ao/dist/N8AO.js'), contentType: 'application/javascript' }));
await page.route('https://fonts.googleapis.com/**', (r) => r.fulfill({ body: '', contentType: 'text/css' }));
await page.route('https://fonts.gstatic.com/**', (r) => r.abort());
await page.goto('http://127.0.0.1:8088/index.html#carte=penitencier'); await page.waitForFunction(() => window.__spReady, null, { timeout: 120000 });
await page.evaluate(() => document.getElementById('soloButton').click());
await page.evaluate(() => { SP.P.hp = SP.P.maxHp = 1e7; SP.sim(0.5); for (const z of [...SP.ZOMBIES]) z.destroy(); SP.G.toSpawn = 0; SP.G.breakT = 1e9;
  const z = new SP.Zombie({ x: 44, z: 32.2, y: 0, kind: 'warden', hp: 1e6, state: 'move', round: 5, yaw: 0 }); z.speed = 0.0001;
  const w = new SP.Zombie({ x: 42.2, z: 33.2, y: 0, kind: 'walker', hp: 1e6, state: 'move', round: 5, yaw: 0.3 }); w.speed = 0.0001;
  SP.P.pos.set(51, 0, 33.5); SP.P.yaw = 1.45; SP.P.pitch = 0.1; SP.sim(0.6); SP.P.pos.set(51, 0, 33.5); SP.P.yaw = 1.45; SP.updatePlayer(0.016); SP.renderFrame(1); });
await page.screenshot({ path: path.join(dir, 'shots', 'boss.png') });
console.log('errors', errors);
await browser.close();
