import { chromium } from 'playwright';
import path from 'path';
const dir = path.dirname(new URL(import.meta.url).pathname);
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 900, height: 506 } });
await ctx.addInitScript(() => { localStorage.setItem('sp_settings', JSON.stringify({ quality: 1 })); });
const page = await ctx.newPage();
const errors = []; page.on('pageerror', (e) => errors.push(e.message + '\n' + e.stack)); page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.text().slice(0, 300)); });
await page.route('https://cdn.jsdelivr.net/npm/three@0.186.1/**', (route) => { const u = new URL(route.request().url()); route.fulfill({ path: path.join(dir, 'node_modules/three', u.pathname.replace('/npm/three@0.186.1/', '')), contentType: 'application/javascript' }); });
await page.route('https://fonts.googleapis.com/**', (r) => r.fulfill({ body: '', contentType: 'text/css' }));
await page.route('https://fonts.gstatic.com/**', (r) => r.abort());
await page.goto('http://127.0.0.1:8088/index.html');
await page.waitForFunction(() => window.__spReady, null, { timeout: 120000 });
await page.click('#soloButton');
const ev = (f, a) => page.evaluate(f, a); const log = (...a) => console.log(...a);
const shot = async (n) => { await ev(() => { SP.renderFrame(1); }); await page.screenshot({ path: path.join(dir, 'shots', n + '.png') }); };
const act = (x, z, yaw, hold = 0) => ev(([x, z, yaw, hold]) => { SP.P.pos.set(x, 0, z); SP.P.yaw = yaw; SP.sim(0.1); SP.INPUT.interactPressed = true; SP.sim(0.1); if (hold) { SP.INPUT.interactHeld = true; SP.sim(hold); SP.INPUT.interactHeld = false; } return document.getElementById('prompt').textContent; }, [x, z, yaw, hold]);
await ev(() => { SP.P.hp = SP.P.maxHp = 1e9; SP.G.me().points = 90000; SP.sim(5); });
for (const [x, z, y] of [[19, 15.3, Math.PI], [19, 37.3, Math.PI], [63, 15.3, Math.PI], [31.4, 49, -Math.PI / 2]]) await act(x, z, y);
await act(11.2, 53, Math.PI / 2); await ev(() => SP.sim(1));
log('after power', JSON.stringify(await ev(() => ({ power: SP.G.power, q: SP.QUEST.stage, spots: SP.QUEST.spots }))));
log('radio', await act(12.4, 28.6, Math.PI / 2), JSON.stringify(await ev(() => ({ q: SP.QUEST.stage, sub: document.getElementById('subtitle').textContent, obj: document.getElementById('objectiveText').textContent }))));
await shot('60_quest_radio');
const spots = await ev(() => SP.QUEST.spots.map((i) => SP.TUBE_SPOTS[i]));
for (const s of spots) log('tube', await act(s[0], s[2], 0), await ev(() => SP.QUEST.taken.join()));
log('install', await act(12.4, 28.6, Math.PI / 2), await ev(() => SP.QUEST.stage));
log('calib', await act(12.4, 28.6, Math.PI / 2, 22), await ev(() => [SP.QUEST.stage, SP.QUEST.calib, SP.QUEST.hold]));
await ev(() => SP.sim(30)); log('hold 30s', await ev(() => [SP.QUEST.stage, SP.QUEST.hold.toFixed(1), SP.G.toSpawn, document.getElementById('objectiveText').textContent]));
await ev(() => SP.sim(62)); await page.waitForTimeout(4500); await ev(() => SP.sim(1));
log('done', await ev(() => [SP.QUEST.stage, SP.G.me().points, document.getElementById('bannerTitle').textContent, SP.ZOMBIES.filter((z) => z.alive).length]));
await shot('61_quest_done');
// Traps.
log('trap', await act(19.1, 19, -Math.PI / 2), await ev(() => SP.TRAPS.map((t) => [t.active.toFixed(0), t.cool])));
await ev(() => { for (const z of [...SP.ZOMBIES]) z.destroy(); const z = SP.spawnTestZombie(19, 21.5); z.hp = 500; SP.sim(0.2); z.pos.set(19, 0, 21); SP.sim(0.3); });
await ev(() => { SP.P.pos.set(19, 0, 18.6); SP.P.yaw = Math.PI; SP.P.pitch = -0.2; SP.sim(0.2); });
await shot('62_trap');
log('trap kill', await ev(() => SP.ZOMBIES.map((z) => [z.state, z.pos.z.toFixed(1)])));
log('ERRORS', errors.length); errors.slice(0, 10).forEach((e) => log(e));
await browser.close();
