import { chromium } from 'playwright';
import path from 'path';
import fs from 'fs';
const dir = path.dirname(new URL(import.meta.url).pathname);
const file = process.argv[2] || path.join(dir, 'index.html');
const out = process.argv[3] || path.join(dir, 'shots');
const scenario = process.argv[4] || 'basic';
fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] }).catch(async () => chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] }));
const ctx = await browser.newContext({ viewport: { width: 1280, height: 720 } });
const page = await ctx.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => errors.push('[pageerror] ' + e.message + '\n' + e.stack));
await page.route('https://cdn.jsdelivr.net/npm/three@0.186.1/**', (route) => { const u = new URL(route.request().url()); const p = path.join(dir, 'node_modules/three', u.pathname.replace('/npm/three@0.186.1/', '')); route.fulfill({ path: p, contentType: 'application/javascript' }); });
await page.route('https://cdn.jsdelivr.net/npm/peerjs@1.5.5/**', (route) => route.fulfill({ path: path.join(dir, 'node_modules/peerjs/dist/peerjs.min.js'), contentType: 'application/javascript' }));
await page.route('https://fonts.googleapis.com/**', (r) => r.fulfill({ body: '', contentType: 'text/css' }));
await page.route('https://fonts.gstatic.com/**', (r) => r.abort());
const t0 = Date.now();
await page.goto('file://' + file);
await page.waitForFunction(() => window.__spReady || document.querySelector('.loading-line.error'), null, { timeout: 120000 });
console.log('ready in', Date.now() - t0, 'ms');
const err = await page.evaluate(() => document.querySelector('.loading-line.error')?.textContent);
if (err) console.log('LOAD ERROR:', err);
await page.waitForTimeout(3000);
await page.screenshot({ path: path.join(out, '01_menu.png') });
if (scenario !== 'menu') {
  await page.click('#soloButton');
  await page.waitForTimeout(4000);
  await page.screenshot({ path: path.join(out, '02_start.png') });
  const info = await page.evaluate(() => ({ mode: SP.G.mode, round: SP.G.round, zombies: SP.ZOMBIES.length, pos: SP.P.pos.toArray(), fps: SP.R.fpsAvg, calls: SP.R.renderer.info.render.calls, tris: SP.R.renderer.info.render.triangles }));
  console.log(JSON.stringify(info));
  await page.waitForTimeout(8000);
  await page.screenshot({ path: path.join(out, '03_round.png') });
  const info2 = await page.evaluate(() => ({ mode: SP.G.mode, round: SP.G.round, zombies: SP.ZOMBIES.map(z => [z.state, z.pos.x.toFixed(1), z.pos.y.toFixed(1), z.pos.z.toFixed(1)]), hp: SP.P.hp, fps: SP.R.fpsAvg }));
  console.log(JSON.stringify(info2));
}
console.log('ERRORS:', errors.length); errors.slice(0, 30).forEach((e) => console.log(e));
await browser.close();
