import { chromium, devices } from 'playwright';
import path from 'path';
const dir = path.dirname(new URL(import.meta.url).pathname);
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ ...devices['iPhone 13 landscape'] });
const page = await ctx.newPage(); const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.route('https://cdn.jsdelivr.net/npm/three@0.186.1/**', (route) => { const u = new URL(route.request().url()); route.fulfill({ path: path.join(dir, 'node_modules/three', u.pathname.replace('/npm/three@0.186.1/', '')), contentType: 'application/javascript' }); });
await page.route('https://fonts.googleapis.com/**', (r) => r.fulfill({ body: '', contentType: 'text/css' }));
await page.route('https://fonts.gstatic.com/**', (r) => r.abort());
await page.goto('http://127.0.0.1:8088/index.html'); await page.waitForFunction(() => window.__spReady, null, { timeout: 120000 });
await page.evaluate(() => document.getElementById('soloButton').click());
await page.evaluate(() => { SP.sim(1); document.body.classList.add('coop'); document.getElementById('team').classList.remove('hidden'); SP.pingNow(); SP.sim(0.2); SP.renderFrame(1); });
await page.screenshot({ path: path.join(dir, 'shots/81_touch_coop.png') });
const boxes = await page.evaluate(() => ['pingButton', 'lightButton', 'pauseButtonTouch', 'team', 'fireButton'].map((id) => { const r = document.getElementById(id).getBoundingClientRect(); return id + ':' + [r.left, r.top, r.right, r.bottom].map(Math.round).join(','); }));
console.log(boxes.join(' | '), 'errors', errors);
await browser.close();
